---
abstract: 'Ascii output of unicode block.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.06
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Unicode-Block-Ascii
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Utils: 0.02
  Error::Pure: 0.16
  Readonly: 0
  Text::UnicodeBox: 0
  Text::UnicodeBox::Control: 0
  Unicode::Block: 0.02
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Unicode-Block-Ascii
  homepage: https://github.com/michal-josef-spacek/Unicode-Block-Ascii
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Unicode-Block-Ascii
version: '0.05'
